language: node_js
node_js: "stable"
install:
  - npm install
  - npm install -g codecov
script:
  - npm test
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coverage
  - npm run test-client
  - codecov
